### ISSUE TITLE
pipeline for base map

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm#10]
base map polygons happen here in our most recent viz:
- https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/fetch.islands.R # get polygons
- https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/utils.R # clip to view limits
- https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/process/process.geopolygons.R # add svg ids
- https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/visualize/visualize.svg_base_map.R # svg prep with more clipping

- make sure this functionality gets transferred into vizstorm
- consider switching to `sf`. if so, leverage how-gdp work at https://github.com/USGS-VIZLAB/how-gdp/blob/master/scripts/fetch/fetch_utils.R#L3-L12
- should we add helpers for bringing in geographic labels for states, oceans, major cities, etc.?
- any aesthetic edits desired in https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/layout/css/hurricane-svg.css?

**Comment by aappling-usgs** [comment]
* should we add helpers for bringing in river networks? looks like this was a start: https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/scripts/fetch/fetch.flowlines.R and https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/scripts/process/process.flowlines.R

**Comment by jordansread** [comment]
Yes, to verify the above - 

The fetchers were set up to only bring in relevant polygons that would be at least partially within the view box. It doesn't _clip_ them, but it does drop polygons that are completely outside of the view

![image](https://user-images.githubusercontent.com/2349007/31258331-0f6c1fe6-aa04-11e7-8cc2-9980366bbab6.png)

The later steps dress up the polygons by adding ids and classes, but don't change the geometries. 

Then the visualize step does additional clipping to cut the vertices out that aren't within the view. The reason for this is to reduce the size of the svg since it doesn't need to contain information about the features outside of the view. 

![image](https://user-images.githubusercontent.com/2349007/31258382-6c164fa0-aa04-11e7-9e25-6c6ca4694891.png)

**Comment by jordansread** [comment]
A note about the flowlines - I think they would be probably good to add, but a couple of drawbacks: 
1) they are really complex, so they add a lot to the DOM (and download size/time of the viz)
2) they presently are made up of a bunch of tiny segments, so they aren't longer polylines that would be easier to apply simplification too (see issues w/ 1 for why we would want to do that). Also, because they aren't a contiguous polyline, we can't apply any fancy styles to them (e.g., [animate them](https://www.doi.gov/water/owdi.cr.drought/en/#Shortage))

**Comment by jordansread** [comment]
I'd propose that the visualize steps in basemap allow us to do special things w/ different classes. 

For example, polygons need to turn into `path` elements. Things that we need the "center" of (dots, or other markers) need to turn into `circle` elements, text should allow us to place `text` elements in certain geographic locations so we don't need to hard code their location after a bunch of [goofy nudging](https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/visualize/visualize.hurricane_map.R#L49), and lines should probably be either `polyline` or `path` (`path` is more flexible...so slight preference). 

We are kind of doing this in `svg_base_map` [here](https://github.com/USGS-VIZLAB/hurricane-irma/blob/564c625b5f06bb9b896168c34f3eeb391b9ede98/scripts/visualize/visualize_utils.R#L59) but it is only for those two classes in that case and is kind of hacky. 

We could learn more about how external graphics devices choose to render svg `circle`s vs `path`s vs `polyline`s within [svglite](https://github.com/r-lib/svglite/tree/master/src) or rely on the knowledge that sp::polygons turn into `path`s and sp::points turn into `circle`s but only if you specify a `pch=20` (or some other circle marker) as a plotting arg. I didn't try to figure out how to get a `sp::lines` to show up as `path` (it is rendered in svg as something else by default) and it wasn't important for earlier storm vizzies.

**Comment by jordansread** [comment]
I think we might want to make this a multi issue set of tasks: one for fetch, one for process, and one for visualize (`svg_base_map`) or something similar.

**Comment by aappling-usgs** [comment]
Thanks for splitting out those pieces. What's left that's specific to this issue - is this one now visualize only?

**Comment by aappling-usgs** [comment]
Regarding earlier comments in this issue thread:
- :+1: on the illustration
- i'm ok with waiting on polylines for the right need & approach, which might come a long time from now; consider it no longer a part of this issue
- should we think about doing the final turning-into-svg step with D3? then the visualize step would just be responsible for creating a simple dataset that D3 can read in?

**Comment by jordansread** [comment]
@aappling-usgs here is my suggestion:

I like the idea (in most cases) of pre-processing the skeleton svg in R and using D3 to make it interactive, because it doesn't increase our load times or download times to include the pre-processed svg map in the DOM (by injecting or otherwise), and this has two nice features: 1) fast render (as quick as the browser can do it) and 2) if the js fails for some reason (or the browser doesn't have js), you still get a map.

But, I really don't want to do much else in pre-processing of visual components, and think the stuff we were doing w/ lots of classes appended together (how we were animating precip cells for other vizzies) should be done instead by D3 and some thoughtful JSON structure that makes this easy. 

So, I think I agree w/ your third point, but with the exception that I still think we can do some initial work to preprocess the svg instead of having D3 build the whole thing.

**Comment by aappling-usgs** [comment]
That makes sense. I agree that load speed should be a high priority, and that we're highly unlikely to want to animate the map itself.

**Comment by jordansread** [comment]
Proposal for code. This is the most complicated use-case that I think we should handle, and maybe it is too complicated to handle generically:

For this example, I want to take a complex geometry and repeat it, but only pay the price of including it in the DOM once. This happens when I want the state styles rendered below and an invisible polygon on top of everything for mouse events.
So, this turns into three commands for the svg: 1) add the `path`s to `defs` using only the geometries and an id that can be referenced, 2) create a style element that only uses CSS and is built from `use` pointing to the path in 1, and 3) a mouseover polygon that only does mouse events and click handler stuff. 

```yaml
process:
  - 
    id: state_geoms_dataframe
    location: cache/state_geoms_dataframe.rds
    reader: rds
    processor: svg_geom_dataframe
    attributes:
      id: '{{ID}}-geom' 
    visualizer_params:
      render: path
      placement: defs
    depends: 
      clip_box: "viewbox_limits"
      spatial_data: "state_map_data"
    scripts: [scripts/process/geom_dataframe.R]
  - 
    id: state_style_dataframe
    location: cache/state_style_dataframe.rds
    reader: rds
    processor: svg_dataframe
    attributes:
      class: state
      href: '#{{ID}}-geom'
      id: '{{ID}}'
    visualizer_params:
      render: use
      placement: map-style
    depends: 
      clip_box: "viewbox_limits"
      spatial_data: "state_map_data"
    scripts: [scripts/process/geom_dataframe.R]  
  - 
    id: state_mouse_dataframe
    location: cache/state_mouse_dataframe.rds
    reader: rds
    processor: svg_dataframe
    attributes:
      onmouseover: hovertext('{{ID}}', evt)
      onmouseout: hovertext(' ')
      class: mouseover
      href: '{{#ID}}-geom'
    visualizer_params:
      render: use
      placement: map-mouse
    depends: 
      clip_box: "viewbox_limits"
      spatial_data: "state_map_data"
    scripts: [scripts/process/geom_dataframe.R] 

visualize:
  -
    id: static_svg_map
    location: cache/static_svg_map.svg
    visualizer: svg_base_map
    depends: 
      states: state_geoms_dataframe
      states-style: state_style_dataframe
      states-mouse: state_mouse_dataframe
    mimetype: image/svg+xml
    scripts: scripts/something.here.R
```

If you didn't need those two separate things repeated, you can always use this:

```yaml
process:
  - 
    id: state_geoms_dataframe
    location: cache/state_mouse_dataframe.rds
    reader: rds
    processor: svg_dataframe
    attributes:
      onmouseover: hovertext('{{ID}}', evt)
      onmouseout: hovertext(' ')
      class: mouseover
      id: '{{ID}}-state'
    visualizer_params:
      render: path
      placement: map-elements
    depends: 
      clip_box: "viewbox_limits"
      spatial_data: "state_map_data"
    scripts: [scripts/process/geom_dataframe.R] 

visualize:
  -
    id: static_svg_map
    location: cache/static_svg_map.svg
    visualizer: svg_base_map
    depends: 
      states: state_geoms_dataframe
    mimetype: image/svg+xml
    scripts: scripts/something.here.R

**Comment by aappling-usgs** [comment]
Well, I said I don't care if the viz.yaml is really long, and I think that's still true, but there's an additional thing happening here: with this pattern of having lots of arguments in the yaml, all these arguments need documentation, and what we've been doing so far is informally adding that documentation to the general text of the function that's defined. And we're relying a bit on existing viz.yaml code to show future viz developers how to use these arguments and which arguments are possible, too.

This is OK...but R offers a more formal system for argument documentation that might be easier for people to navigate. Each of those 3 process items in the first example could call a wrapper function to svg_dataframe whose main job would be to define the appropriate arguments and pass them to svg_dataframe. svg_dataframe could be defined as a separate helper function, and the arguments to that function could include things like `render` and `placement` - then the existence of those arguments would be clear from the formals of `svg_dataframe` and their definitions could be given as `@param` entries.

A tension here is between having information super-visible in the viz.yaml or having it partly visible in a script specific to one or a few viz items. (Though note also that visibility declines as the viz.yaml gets longer, so as the amount of info grows, the visibility always declines.) We put a whole lot of other custom information in scripts, and I think that's appropriate - in fact, because most non-storm vizzies are one-off, just about all the information in every script is 'custom' to that vizzie. I think the stuff that **needs** to live in the viz.yaml is stuff that (1) we're going to experiment with really really often or (2) gets shared or coordinated across several viz items. It's satisfying to look at a single viz item and be able to see all the super-relevant information right there in the yaml, but we could also make that information fairly quick to access and find by putting it at the top of a wrapper function - I think we have this choice.

For the specific example above, these two chunks could potentially form the bulk of the code within R functions whose jobs are to (1) define those params and (2) call svg_dataframe and (3) quit.:
```
    attributes:
      onmouseover: hovertext('{{ID}}', evt)
      onmouseout: hovertext(' ')
      class: mouseover
      href: '{{#ID-geom}}'
    visualizer_params:
      render: use
      placement: map-mouse
```
The `id` and `href` attributes do need some coordination across the 3 items, and i could see this happening either in the viz.yaml or within a single R script that defines all 3 of those wrapper functions.

So...nothing really wrong with what's proposed above, and if you're feeling committed then go for it, but let's keep open this conversation about the philosophy of what needs to live where and why.
