### ISSUE TITLE
function and helper functions for process.map_geoms

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/vizstorm#24]
Spinoff of #10 

I am assuming this takes the geoms coming out of `fetch` and makes them ready for an easier pass to `visualize`

In the hurricanes, we added ids and anything else that would end up as attributes to the elements that end up in the svg (e.g., `mouseover`, `class`, etc). I think we should go a little further and do the clipping to the `viewbox_limits` at the process stage instead of in visualize. Additional information coming out of the `process` stage might also include how these geoms get turned into svg (e.g., are they `path`,`circles`, `text`?)

More complicated, and maybe part of the challenge of implementing `visualize.base_map` or js functions that use the base map, is how to specify whether these geoms end up being placed in `<defs>` and recycled efficiently as `<use>` elements (which allow us to repeat complex elements w/o adding too much to the DOM) or end up directly entering the rendered parts of the svg as `<path>` or other elements (`defs` is where things go that are never rendered directly). 

We often would want to use `defs` and then `use` if we repeat a complex geometry, and the most common use case I can think of is having one copy of the geom be used as styling, and another copy sitting on top of things but otherwise invisible, which is used only for catching mouse events. 

If not using mouse events (just style), it may not be much of a cost to combine `use` and `defs` (the case where `use` would only show up once per geometry added to `defs`), which would make the coding simpler.

**Comment by jordansread** [comment]
Referencing prototype done in #25. 
My assumption with this work is that we are moving more towards implementing interactions with D3 and less of doing those things in R. 
Goals: 

1. generic function for clipping and adding attributes to spatial data (trying to avoid writing custom functions for each set of spatial data, because they all end up being a bit different: counties, gages, states, islands, cells, etc). 
2. Can be edited by someone more familiar w/ js than R to get the svg attributes set up the way they want 
3. have things that will show up in css (e.g., ids or classes) in yaml parameters, instead of buried in code. 
4. make the attribute inputs unlimited, not preset to a limited number of function defaults. #25 uses `...` to do this. 

I proposed a set of functions and viz.yaml syntax to (hopefully) edit w/o diving into R functions:
```yaml
  - 
    id: state_geoms_dataframe
    location: cache/state_geoms_dataframe.rds
    reader: rds
    processor: geom_dataframe
    eval_args:
      class: I("state")
      mouseover: "sprintf('hovertext(\"%s\", evt)', name)"
      mouseout: I("hovertext(\" \")")
```
because the function uses non-standard eval (to evaluate `sprintf('hovertext(\"%s\", evt)', name)` within an environment that contains the variable the data associated with the spatial data dependency, which has a data.frame with `name` in it) 
NSE makes this yaml more complicated, but is flexible because you can reference any function available. 

This is possible because `do.call` can expand and evaluate anything in `...`. Blodgett noted an aversion to `do.call`, but I consider it to be a core R function that shouldn't be avoided because of the complexity of its syntax. 

So - I'd like feedback on the *Goals* noted above (are they offbase?) and thoughts on tradeoffs between viz.yaml syntax simplicity and flexibility. 

Note to self- modifying the name of `eval_args` to `attributes` would be more intuitive to developers that don't need to be familiar with NSE.

**Comment by dblodgett-usgs** [comment]
Given the goals stated here, a lot of my critique is not very relevant. I am supportive of this in concept. One use case to consider that I'm thinking about is things like hovertext that is relative to some geometry in the viz rather than the `evt`. In that case, you would need a bit of logic (written in R not the viz.yml) to create the hovertext right? Would this pattern imply some function you'd write that would go in pace of evt? Maybe I'm not seeing the big picture because I have a limited JS background though, in which case, carry on, I'm not going to be the best judge in that case.

**Comment by jordansread** [comment]
Blodgett, I would assume that special case would be covered more by js. But this implementation doesn't stop you from writing more complex stuff in R either way. And you can always write a different process method that is specialized.

**Comment by jordansread** [comment]
I'm wondering what is more important - better syntax for users in the yaml vs easier to read code in the functions. Regardless, one potential solution to the yaml:

```yaml
process:
  - 
    id: state_geoms_dataframe
    location: cache/state_geoms_dataframe.rds
    reader: rds
    processor: geom_dataframe
    attributes:
      class: state
      mouseover: hovertext('{ID}, evt')
      mouseout: hovertext(' ')
    depends: 
      clip_box: "viewbox_limits"
      spatial_data: "state_map_data"
    scripts: [scripts/process/geom_dataframe.R]
```
this requires some knowledge of the available data in `state_map_data`, which here has an ID column in the data.frame

Switching to this syntax, which is much much simpler, would also be limiting. Instead of allowing the evaluation of any R function with the context of the data.frame, this would only support simple character substitution.
